In [63]:
import pandas as pd
import numpy as np
import datetime

In [64]:
total_df = pd.read_csv('News Sentiment/news_sentiment.csv')

In [65]:
dates = [datetime.datetime(int(x.split('/')[3]), int(x.split('/')[4]), int(x.split('/')[5])) for x in total_df['url']]
total_df['Date'] = dates

total_df.columns

Index(['url', 'timedelta', 'n_tokens_title', 'n_tokens_content',
       'n_unique_tokens', 'n_non_stop_words', 'n_non_stop_unique_tokens',
       'num_hrefs', 'num_self_hrefs', 'num_imgs', 'num_videos',
       'average_token_length', 'num_keywords', 'data_channel_is_lifestyle',
       'data_channel_is_entertainment', 'data_channel_is_bus',
       'data_channel_is_socmed', 'data_channel_is_tech',
       'data_channel_is_world', 'kw_min_min', 'kw_max_min', 'kw_avg_min',
       'kw_min_max', 'kw_max_max', 'kw_avg_max', 'kw_min_avg', 'kw_max_avg',
       'kw_avg_avg', 'self_reference_min_shares', 'self_reference_max_shares',
       'self_reference_avg_sharess', 'weekday_is_monday', 'weekday_is_tuesday',
       'weekday_is_wednesday', 'weekday_is_thursday', 'weekday_is_friday',
       'weekday_is_saturday', 'weekday_is_sunday', 'is_weekend', 'LDA_00',
       'LDA_01', 'LDA_02', 'LDA_03', 'LDA_04', 'global_subjectivity',
       'global_sentiment_polarity', 'global_rate_positive_words',
       'global_rate_negative_words', 'rate_positive_words',
       'rate_negative_words', 'avg_positive_polarity', 'min_positive_polarity',
       'max_positive_polarity', 'avg_negative_polarity',
       'min_negative_polarity', 'max_negative_polarity', 'title_subjectivity',
       'title_sentiment_polarity', 'abs_title_subjectivity',
       'abs_title_sentiment_polarity', 'shares', 'Date'],
      dtype='object')

In [66]:
df = total_df[['Date', 'data_channel_is_lifestyle',
       'data_channel_is_entertainment', 'data_channel_is_bus',
       'data_channel_is_socmed', 'data_channel_is_tech',
       'data_channel_is_world', 'global_subjectivity', 'global_sentiment_polarity', 'global_rate_positive_words',
       'global_rate_negative_words', 'rate_positive_words',
       'rate_negative_words', 'avg_positive_polarity', 'min_positive_polarity',
       'max_positive_polarity', 'avg_negative_polarity',
       'min_negative_polarity', 'max_negative_polarity', 'title_subjectivity',
       'title_sentiment_polarity', 'abs_title_subjectivity',
       'abs_title_sentiment_polarity', 'shares']]

df.head()

,Date,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,global_subjectivity,global_sentiment_polarity,global_rate_positive_words,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,2013-01-07,0,1,0,0,0,0,0.521617,0.092562,0.045662,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,2013-01-07,0,0,1,0,0,0,0.341246,0.148948,0.043137,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,2013-01-07,0,0,1,0,0,0,0.702222,0.323333,0.056872,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,2013-01-07,0,1,0,0,0,0,0.429850,0.100705,0.041431,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,2013-01-07,0,0,0,0,1,0,0.513502,0.281003,0.074627,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [67]:
df_gp_date = df.groupby('Date',as_index=False).mean()

df_gp_date.head()

,Date,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,global_subjectivity,global_sentiment_polarity,global_rate_positive_words,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,2013-01-07,0.101266,0.088608,0.113924,0.050633,0.455696,0.113924,0.480690,0.176541,0.052167,...,0.095476,0.814768,-0.233600,-0.461920,-0.095057,0.311666,0.025181,0.329081,0.176808,2004.556962
1,2013-01-08,0.083333,0.166667,0.083333,0.000000,0.416667,0.166667,0.455641,0.161938,0.048414,...,0.120896,0.791667,-0.242193,-0.504167,-0.090625,0.238889,0.086111,0.338889,0.102778,1493.583333
2,2013-01-09,0.134831,0.191011,0.112360,0.033708,0.235955,0.123596,0.467116,0.145615,0.046497,...,0.110150,0.781581,-0.276591,-0.521540,-0.117911,0.250849,0.051133,0.385071,0.159139,2536.303371
3,2013-01-10,0.125000,0.187500,0.200000,0.012500,0.237500,0.062500,0.462260,0.156578,0.047305,...,0.099115,0.765076,-0.244383,-0.501389,-0.091443,0.199863,0.040592,0.389721,0.096425,2085.200000
4,2013-01-11,0.098039,0.137255,0.078431,0.058824,0.333333,0.156863,0.480836,0.166839,0.043516,...,0.102568,0.830392,-0.244791,-0.497358,-0.101171,0.354147,0.053680,0.329093,0.186686,3621.843137

In [68]:
google_data = pd.read_csv('Stocks/googl.us.txt')

google_data.head()

         Date    Open   High     Low   Close    Volume  OpenInt
0  2004-08-19  50.000  52.03  47.980  50.170  44703800        0
1  2004-08-20  50.505  54.54  50.250  54.155  22857200        0
2  2004-08-23  55.375  56.74  54.525  54.700  18274400        0
3  2004-08-24  55.620  55.80  51.785  52.435  15262600        0
4  2004-08-25  52.480  54.00  51.940  53.000   9197800        0

In [69]:
df = df_gp_date.set_index('Date').join(google_data.set_index('Date'))

df.head()

,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,global_subjectivity,global_sentiment_polarity,global_rate_positive_words,global_rate_negative_words,...,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares,Open,High,Low,Close,Volume,OpenInt
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-07,0.101266,0.088608,0.113924,0.050633,0.455696,0.113924,0.480690,0.176541,0.052167,0.015850,...,0.025181,0.329081,0.176808,2004.556962,367.72,369.69,365.29,367.38,3311534.0,0.0
2013-01-08,0.083333,0.166667,0.083333,0.000000,0.416667,0.166667,0.455641,0.161938,0.048414,0.015218,...,0.086111,0.338889,0.102778,1493.583333,367.77,368.15,362.22,366.65,3352074.0,0.0
2013-01-09,0.134831,0.191011,0.112360,0.033708,0.235955,0.123596,0.467116,0.145615,0.046497,0.015021,...,0.051133,0.385071,0.159139,2536.303371,366.50,369.18,364.30,369.06,4051302.0,0.0
2013-01-10,0.125000,0.187500,0.200000,0.012500,0.237500,0.062500,0.462260,0.156578,0.047305,0.017239,...,0.040592,0.389721,0.096425,2085.200000,371.42,372.50,366.75,370.74,3671560.0,0.0
2013-01-11,0.098039,0.137255,0.078431,0.058824,0.333333,0.156863,0.480836,0.166839,0.043516,0.016712,...,0.053680,0.329093,0.186686,3621.843137,371.00,371.22,368.15,370.00,2570250.0,0.0

In [70]:
df.to_csv('news_sentiment_augmented_google.csv')